### ISSUE TITLE
Shows a second black row if the itemsource has only one element

### ISSUE THREAD

**Issue by WeierE1** [akgulebubekir/Maui.DataGrid#126] opened 2023-09-25 08:14 UTC
If the itemsource has only one element, a second black row is displayed. If the itemsource has more than one item everything is fine.

![ItemsourceHasOnlyOneItem](https://github.com/akgulebubekir/Maui.DataGrid/assets/143438176/4f70f411-ad1e-40e3-abc0-2481e9a893eb)
![ItemsourceHasTwoOrMoreItems](https://github.com/akgulebubekir/Maui.DataGrid/assets/143438176/457f525c-4c0a-4094-9b7d-091e934d9cc1)

**Comment by WeierE1** [comment] 2023-09-25 13:24
I have now been able to figure out the problem.
The reason is that the RefreshView has a relatively large standard height. That means if the Collection view has no entries or only very few with a low RowHeight the CollectionView is simply enlarged and then shows its background color.
I have solved this with modifing the method OnBindingContextChanged and the internal property InternalItems
1. OnBindingContextChanged Method
`protected override void OnBindingContextChanged()
    {
        base.OnBindingContextChanged();
        _refreshView.HeightRequest = _internalItems != null ? _internalItems.Count * RowHeight : 0;
        InitHeaderView();
    }`

  2. InternalItems Property
    `internal IList<object>? InternalItems
    {
        get => _internalItems;
        set
        {
            if (_internalItems != value)
            {
                _internalItems = value;
                _refreshView.HeightRequest = _internalItems != null ? _internalItems.Count * RowHeight : 0;
                _collectionView.ItemsSource = _internalItems; // TODO: Are we using the most efficient CollectionChanged handling with observables?
            }
        }
    }`

**Comment by symbiogenesis** [comment] 2023-09-26 06:15
I think this is expected behavior, and your solution works for you.

If you were going to adapt this to be a PR, then you would have some kind of toggle for a dynamic height, and the height request update would be extracted into a function that is shared in those two places.

But I will close this, since it is not a bug.

**Closed by symbiogenesis** 2023-09-26 06:15 UTC
