### ISSUE TITLE
Performance issues with Mac Catalyst

### ISSUE THREAD

**Issue by akgulebubekir** [akgulebubekir/Maui.DataGrid#78] opened 2023-02-09 21:17 UTC
There is significant performance issue on Mac Catalys since commit 3d6dfc5988432f153e9cd128edaf4d697373d528. It also consumes more memory. Its probably same with other platforms. @symbiogenesis  can you have a look at that?

**Comment by symbiogenesis** [comment] 2023-02-09 23:42
Made a lot of extra performance-related changes since 2.0.0 including:

- https://github.com/akgulebubekir/Maui.DataGrid/pull/77
- https://github.com/akgulebubekir/Maui.DataGrid/pull/76
- https://github.com/akgulebubekir/Maui.DataGrid/pull/74
- https://github.com/akgulebubekir/Maui.DataGrid/pull/68
- https://github.com/akgulebubekir/Maui.DataGrid/pull/63
- https://github.com/akgulebubekir/Maui.DataGrid/pull/51

I have also fixed some issues such as:

- https://github.com/akgulebubekir/Maui.DataGrid/issues/70
- https://github.com/akgulebubekir/Maui.DataGrid/issues/55
- https://github.com/akgulebubekir/Maui.DataGrid/issues/53

I have another queued up change to set colors less. MAUI itself also has some major issues that they are trying to resolve:

[This pull request](https://github.com/dotnet/maui/pull/13232) should help when it is merged.

**Comment by symbiogenesis** [comment] 2023-02-09 23:48
The memory usage of the CollectionView has been very bad going back to Xamarin.Forms, and they never fully fixed it. There are other issues beyond that recent pull request.

There are multiple collection view projects and branches that try to improve things. Unfortunately, most such projects don't work on every MAUI platform.

See also:

- https://github.com/dotnet/maui/issues/12130#issuecomment-1422570083
- https://github.com/dotnet/maui/issues/12039#issuecomment-1424888066

**Comment by symbiogenesis** [comment] 2023-02-09 23:50
Deploying a .NET 7.0 version to nuget may help a little, since only the .NET 6.0 version made it over.

**Comment by symbiogenesis** [comment] 2023-02-10 04:06
I found a way to reliably reproduce and test a case with bad performance.

My findings so far:

Reverting the ContentView wrapper: _**No visible improvement**_
Reverting to the DataTemplateSelector: _**No visible improvement**_
Reverting the WeakReference wiring for events: _**No visible improvement**_
Reverting the LineBreakMode: _**No visible improvement**_
Removing the IsVisible binding: _**No visible improvement**_

I also tried moving the _headerGrid inside of the HeaderTemplate of the CollectionView. This had no positive impact, but made the header no longer sticky at the top, and thus was worse.

My opinion is that MAUI has internal bugs, and that it potentially even worsened recently, such as with their recent Grid calculation changes.

**Comment by symbiogenesis** [comment] 2023-02-10 20:51
I alerted the MAUI team in that memory leaks issue posted above. The developer Jonathan Peppers from the MAUI team is looking into this right now, and found an issue.

**Closed** 2023-04-08 22:25 UTC
