### ISSUE TITLE
SortedColumnIndex BindingMode "TwoWay"

### ISSUE THREAD

**Issue by SE250880** [akgulebubekir/Maui.DataGrid#123] opened 2023-08-22 07:46 UTC
I´m using your control for my IOS Maui App. 
I just want to set the sortOrder in the background as well. So I bind the sortorder to a viewmodel property and set the binding mode "Two way" in xaml file (SortedColumnIndex="{Binding SortIndex,Mode=TwoWay}"). But this leads to an NullReferenceException.

What am I doing wrong?

Furthermore I also have trouble with the SelectedItem property. I bind it two way in xaml: SelectedItem="{Binding SelectedDefect,Mode=TwoWay}, because I want to change the selection in the Background. But sometimes the datagrid don´t show the selection or it show 2 selected items, but I only have one selected item in the background.

**Comment by symbiogenesis** [comment] 2023-08-24 23:13
The code is super simple, and doesn't rely on any platform-specific rendering. I recommend pulling the repository into your codebase, and then stepping through it with the debugger to find the problem. Then submit a PR.

Also MAUI has lots of bugs and you should keep an eye on whether any of them match what you are seeing, and keep an eye on when it is fixed.

If you want me or someone else to take a look at this, you should build a minimal reproducible test case using the included SampleApp as a starting point, and state which MAUI version (including the point release) you are using.

Also it would be best to break up the issues into individual issues, so that they can be addressed individually.

**Comment by SE250880** [comment] 2023-08-25 10:20
Thanks for your reply.
To find the error with the sorting issue I set  SortedColumnIndex="{Binding SortIndex,Mode=TwoWay}" and debugged the code. In the screenshot zu see the exception and the sourceposition where it occurs. Hope this helps.
![grafik](https://github.com/akgulebubekir/Maui.DataGrid/assets/34155651/e32d8c71-126b-4750-b7ce-9bf55fe4e870)

**Comment by SE250880** [comment] 2023-08-31 05:30
So, I further debugged the datagrid and found that the error comes from the rotating icon function.
I am using .Net 8 Prev. 5.
![grafik](https://github.com/akgulebubekir/Maui.DataGrid/assets/34155651/13cd2482-bd35-4d86-bb7d-0d763630dbdc)

In your sample code you use .Net7 and it works, so this seems to be a Maui bug?

**Comment by symbiogenesis** [comment] 2023-08-31 16:13
I have found that being active on the official MAUI github is useful, because if you can build a minimal reproducible test case then they can try to fix the problem.

I would consider upgrading to .NET 8 Preview 7 before making a bug report, though.

**Comment by symbiogenesis** [comment] 2023-12-27 08:51
Still a problem with .NET 8, and/or the latest master branch? Closing until I hear otherwise.

**Closed by symbiogenesis** 2023-12-27 08:51 UTC
